### PR TITLE
Milestone #3: Creating Data Models

### PR DESCRIPTION
**Pull request by Anjacodes**
In this milestone, I:

* Built my project schema.
   -> Created and ran the necessary migration files.
   -> Made sure that table and column names match the ERD diagram.
   -> Made sure that foreign keys are included.
   -> All columns that are foreign keys have a corresponding index.
* Made sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
* Made sure to use correct flow [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
* Made sure to document my work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)[](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/creating_data_model_project.md#ruby-requirements).
* Followed the list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

### CODE REVIEW

**Comment by Anjacodes** [comment]
Dear TSE, GitHub actions are currently down, which is why linters do not run remotely. Kindly run the linters locally, as recommended by [David Bassey](https://app.slack.com/team/U016SV2LQ48) on Slack:
[@Anja Schmidt](https://microverse-students.slack.com/team/U02GCACA8P7) kindly go ahead with your review request with a message to the reviewer stating that GitHub actions are currently down and linters check can be done locally in the meantime.
Thank you for your understanding!

**Review by omar-labana — APPROVED** [review]
# **Approved ✔️**

Hi @Anjacodes,

- [ ] _[OPTIONAL]_ For future projects, kindly consider kebab case naming for DB tables. It's kinda the "rails convention".

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Anjacodes** [comment]
Thank you @omar-labana! 🙏 This is the first time I hear about kebab case naming 😅 I found this definition: Kebab case -- or kebab-case -- is a programming variable naming convention where a developer replaces the spaces between words with a dash. Is that what you mean?

**Comment by omar-labana** [comment]
@Anjacodes yep, a ruby convention

**Pull request merged**
